# Generated by Django 3.2.8 on 2021-11-03 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsreview',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clientsreview',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='clientsreview',
            name='review',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='clientsreview',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='clientsreview',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
